# Introducción de R en google colab


## Habilitar R

Cuándo se abre google colab el lenbguaje base es siempre python, pero existe una forma de trabajar con R también. 

1- Primero hay que abrir el navegador

2- Colocar alguna de las siguientes URL:
  
   - https://colab.research.google.com/#create=true&language=
   - https://colab.to/r

Para poder ingresar tienen que tener abierta su sesion de Google drive

Google Colaboratory proporciona la posibilidad de trabajar en la nube lo que permite usar el potencial de máquina que ofrece google. No es el único que trabaja de esta manera, existen otras plataformas que trabajan igual:

- Binder: https://mybinder.org/ es gratuito pero hay que tener el código en github. Trabaja R, Python y Julia
- Kaggle: https://www.kaggle.com/ ideal para practicar además tiene bases de datos disponibles. Trabaja R y Python
- Microsoft Azure: ofrece horas gratis pero es de pago
- JetBrains datalore : También tiene horas gratis el resto es pago



## Estructuras de datos

### Vectores en R

Los vectores siempre contienen elementos de un mismo tipo. Se construyen con la función c. Si se agrega un dato de tipo distino a los que tiene el vector este transforma todos los datos en en tipo más genérico que pueda soportar a todos los elementos que contiene.

In [19]:
x <- c(5,6,8)
x

[1] 5 6 8

Para elegir un elemento se pone su posición entre corchetes. Esté además puede ser modificado por lo que es un objeto de tipo mutable

In [20]:
x[2] <- 7
x

[1] 5 7 8

### Matrices y arrays

Las matrices se podrían considerar como vectores de  dos dimensiones, por lo tanto al igual que un vector pueden tener datos de un solo tipo. Un array es una generalización de las matrices y puede adoptar cualquier dimensión, aunque también es encesario qeu sean del mismo tipo los elementos. En machine learning se usan mucho los tensores que son arrays de matrices.

Para crear una matriz se utiliza el comando *matrix()*. Esta función acepta un argumento que son los datos y luego dos argumentos más que son el número de filas *nrows* y el número de columnas *ncol*. 


In [21]:
A <- matrix(1:12, 3,4 )
A

[,1] [,2] [,3] [,4]
[1,] 1    4    7    10  
[2,] 2    5    8    11  
[3,] 3    6    9    12

Para elegir un elemento de le matriz, se debe indicar el número de fila y el número de columna en el cual está el elemento

In [22]:
A[2,3]

[1] 8

También se puede elegir un elemento marcando la posición que tiene el elemento contando como si fuera un vector

In [24]:
A[5]

[1] 5

En caso que se quiera seleccionar una fila o una columna entera no se pone nada en esa posición y se acompaña la coma. $M[f,]$ para elegir una fila, $M[,c]$ para elegir una columna

In [23]:
A[2,]

[1]  2  5  8 11

Otra forma de crear matrices es con las funciones *cbind* y *rbind* para apilar vectores en columnas y vectores en filas respectivamente

In [25]:
cbind(c(1:4), c(2:5))

[,1] [,2]
[1,] 1    2   
[2,] 2    3   
[3,] 3    4   
[4,] 4    5

In [27]:
rbind(c(1:4), c(2:5))

[,1] [,2] [,3] [,4]
[1,] 1    2    3    4   
[2,] 2    3    4    5

### Data frames

Los data frames son matrices que pueden adoptar cualquier tipo de dato. Son muy utilizados para trabajar, porque es el formato que adopatan las bases de datos. Las columnas de un dataframe son vectores, por lo tanto solo aceptan datos de un solo tipo, en el caso de las filas si se aceptan diferentes tipo de datos.

Para crear un data frame se usa la función *data.frame()* y se le pueden agregar nombres a las columnas


In [31]:
mi_df <- data.frame(
  "entero" = 1:4, 
  "factor" = c("a", "b", "c", "d"), 
  "numero" = c(1.2, 3.4, 4.5, 5.6)
  #"cadena" = as.character(c("a", "b", "c", "d"))
)

mi_df

entero factor numero
1 1      a      1.2   
2 2      b      3.4   
3 3      c      4.5   
4 4      d      5.6

In [32]:
# la función dim arroja la cantidad de filas y columnas que tiene el df

dim(mi_df)

[1] 4 3

In [33]:
# la función length arrija la cantidad de columnas
length(mi_df)

[1] 3

Para seleccionar elementos se trabaja de la misma forma que para una matriz, con un adicional, acá se puede elegir una columna de acuerdo al nombre que le hayamos puesto

In [34]:
mi_df['factor']

factor
1 a     
2 b     
3 c     
4 d

In [40]:
# fila 3 de la columna factor
mi_df[3,'factor']

[1] "c"

### Listas

Las listas son unidimensionales como los vectores, pero pueden contener cualquier elemento dentro de ellas, incluso otras listas. Se pueden crear con la función *list()*

In [41]:
lista1 <- list(c(5,4), matrix(1:4,2,2), 4,'pepe')
lista1

[[1]]
[1] 5 4

[[2]]
     [,1] [,2]
[1,]    1    3
[2,]    2    4

[[3]]
[1] 4

[[4]]
[1] "pepe"

In [42]:
lista2 <- list(lista1, mi_df)
lista2

[[1]]
[[1]][[1]]
[1] 5 4

[[1]][[2]]
     [,1] [,2]
[1,]    1    3
[2,]    2    4

[[1]][[3]]
[1] 4

[[1]][[4]]
[1] "pepe"


[[2]]
  entero factor numero
1      1      a    1.2
2      2      b    3.4
3      3      c    4.5
4      4      d    5.6

## Condicionales if y else

La función if sirve para ejecutar una dfeterminada función siempre que ocurra alguna condición en particular. La estructura de la misma en R se escribe de la siguiente forma:

if (condición) {

    operaciones

    }
    
Esto nos dice que va hacer el programa cuando ocurra la condición, en caso de que esto no suceda no va pasar nada. Si queremos agregar operaciones que actuén en caso de falsedad de la condicíon hay que agregar el comando *else*

if (condición) {
    
    opearciones si se cumple
    
    } else 
    {
    
    operaciones si no se cumple
    
    }
  

**Ejemplo**

Excluir la división por 0

In [9]:
n = 6
d = 2

if (d != 0){
    print (n/d)
    } else 
    {
    print('no se puede dividir por 0')
          }


[1] 3


### ifesle

El comando ifelse opera cuando queremos trabajar sobre listas, nos va devolever el grado de verdad por cada elemento de la lista.

Estructura:

ifelse( vector y condición, valor si es verdadero, valor si es falso)


In [11]:
n = 6
d = c(0,2,3)

ifelse(d == 0, 'No se puede dividir', 6/d) 

[1] "No se puede dividir" "3"                   "2"

## Iterar en R

Una de las funciones principales para crear un programa es manejar las iteraciones o bucles

### Instrucción for

for (i in secuencia) {
  
      operación 1
  
      ...
  
      operación final
  
    }

**Ejemplo** 

Multiplicación de dos vectores 

In [ ]:
a <- c(2,6,4)
b <- c(5,7,2)

rdo <- numeric()  #creamos un vector vacío

for (i in 1:length(a)){
  x <- a[i]*b[i]
  rdo[i] <- x
}

rdo

[1] 10 42  8

In [ ]:
a*b

[1] 10 42  8

instrucción while

while (condición) {

  operación 1

  ...

  operación final 
  
}


**Ejemplo**

Serie de Fibonacci

In [ ]:
max <- 10 
i <- 0  #iterador
rdo <- numeric()

while (i < max) {
  if (length(rdo) < 2) {
     rdo[i] <- 1
      }
  else{
    rdo[i] <- rdo[i-1]+rdo[i-2]
  }
  i <- i+1  #importante para no tener un bucle infinito
}

rdo

[1]  1  1  2  3  5  8 13 21 34

## Funciones

Estructura

nombre_de_función <- function(variable1, variable2,...){
  
    cuerpo

    return(resultado)
  }


Por ejemplo función que devuelve la serie de Fibonacci

In [ ]:
Fibonacci <- function(cantidad_digitos){
  i <- 0  #iterador
  rdo <- numeric()

while (i <= cantidad_digitos) {
  if (length(rdo) < 2) {
     rdo[i] <- 1
      }
  else{
    rdo[i] <- rdo[i-1]+rdo[i-2]
  }
  i <- i+1  #importante para no tener un bucle infinito
}

return(rdo)

}

In [ ]:
Fibonacci(8)
Fibonacci(6)

[1]  1  1  2  3  5  8 13 21

[1] 1 1 2 3 5 8

## Montar una imágen de google drive

In [ ]:
install.packages("googledrive")
library(googledrive)

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)



In [ ]:
if (file.exists("/usr/local/lib/python3.6/dist-packages/google/colab/_ipython.py")) {
  install.packages("R.utils")
  library("R.utils")
  library("httr")
  my_check <- function() {return(TRUE)}
  reassignInPackage("is_interactive", pkgName = "httr", my_check) 
  options(rlang_interactive=TRUE)
}

In [ ]:
drive_auth(use_oob = TRUE, cache = TRUE)

ERROR: ignored

In [ ]:
options(gargle_oauth_email = "pabanib@hotmail.com")
drive_auth(email = "pabanib@hotmail.com")

ERROR: ignored

In [ ]:
drive_find()

ERROR: ignored

In [ ]:
help(drive_auth)